In [3]:
import pandas as pd
import seaborn as sns

In [2]:
ann_vars = pd.read_csv("/storage/mathelierarea/processed/eirikhoy/action_var/results/expecto_annotated_variants.csv")
ann_vars

,chrom,snp_chromStart,snp_chromEnd,SNP,ref,alt,chrom_gene,tss,tss_chromEnd,strand,...,Macro_m1_CCL,plasma_IgA,Fibro_SFRP4,Lumsec_HLA,Mono_non_classical,LummHR_active,Macro_IFN,CD4_activated,Fibro_major,pDC
0,1,45794979,45794980,1_45794979_C_G,C,G,1,45792568,45792569,+,...,-0.058157,-0.086031,-0.202274,-0.101641,-0.034030,-0.114761,-0.046459,-0.035442,-0.163672,-0.082305
1,1,45794983,45794984,1_45794983_G_A,G,A,1,45792568,45792569,+,...,0.069310,-0.019523,0.158286,-0.343143,0.071504,-0.189323,0.095811,-0.039422,0.146556,0.040003
2,1,45794993,45794994,1_45794993_G_A,G,A,1,45792568,45792569,+,...,-0.162856,-0.321782,-0.525595,-0.224855,-0.117842,-0.203701,-0.158149,-0.265682,-0.417115,-0.308078
3,1,45794998,45794999,1_45794998_G_C,G,C,1,45792568,45792569,+,...,0.009364,0.034013,0.037675,0.088051,0.004546,0.093291,0.009438,0.037924,0.036089,0.015332
4,1,45795002,45795003,1_45795002_G_A,G,A,1,45792568,45792569,+,...,0.066755,0.052820,0.095924,0.184090,0.052263,0.155310,0.050283,-0.003054,0.116481,0.039094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10116,8,90996799,90996800,8_90996799_T_A,T,A,8,90996871,90996872,-,...,-0.481346,0.174968,-0.753059,0.088084,-0.440934,0.022356,-0.395922,0.338504,-0.713791,-0.032397
10117,8,90996805,90996806,8_90996805_G_A,G,A,8,90996871,90996872,-,...,-0.445344,-0.257611,-0.200781,-0.274405,-0.373441,-0.157192,-0.629108,0.134022,-0.226881,-0.418884
10118,8,90996810,90996811,8_90996810_G_A,G,A,8,90996871,90996872,-,...,-0.188455,0.278797,0.250662,0.539204,-0.102425,0.595538,-0.173763,0.941237,0.069983,0.282454
10119,8,90996815,90996816,8_90996815_C_T,C,T,8,90996871,90996872,-,...,0.607266,1.053853,0.964517,1.646350,0.322142,1.211496,0.695169,1.030406,0.798057,0.799901
10120,8,90996827,90996828,8_90996827_G_C,G,C,8,90996871,90996872,-,...,-0.511601,-1.320631,-0.590257,-1.162134,-0.429424,-1.289775,-0.516754,-1.330559,-0.380444,-1.191755

In [ ]:
sns.scatterplot(
    x=
)

In [9]:
meta_cols = ['chrom', 'snp_chromStart', 'snp_chromEnd', 'SNP', 'ref', 'alt',
                'chrom_gene', 'tss', 'tss_chromEnd', 'strand', 'gene_name', 'gene_id',
                'cage_used', 'dist', 'feature_type', 'overlapping_transcripts',
                'genes_overlapping_variant', 'position_vs_tss', 'max_abs_z',
                'max_abs_z_celltype', 'mean_z', 'n_celltypes_abs_z_ge_2'
                ]

cell_cols = ['Vas_venous', 'pericytes', 'Lumsec_myo', 'CD8_Tem', 'macro_mean',
       'b_naive', 'Lumsec_basal', 'CD8_activated', 'Lymph_valve1',
       'Fibro_prematrix', 'Lymph_major', 'CD4_Tem', 'plasma_IgG', 'mDC',
       'CD8_Trm', 'bmem_unswitched', 'CD4_Th_like', 'mye_prol', 'basal',
       'Neutrophil', 'Mono_classical', 'LummHR_major', 'GD', 'Mast', 'NK',
       'Macro_lipo', 'LummHR_SCGB', 'CD4_Treg', 'Lymph_immune', 'cDC1',
       'Macro_m1', 'Fibro_matrix', 'Lumsec_KIT', 'NKT', 'Lumsec_lac',
       'Vas_capillary', 'bmem_switched', 'Macro_m2_CXCL', 'NK_ILCs',
       'Macro_m2', 'vsmc', 'Lumsec_prol', 'CD4_Th', 'cDC2', 'Macro_m1_CCL',
       'plasma_IgA', 'Fibro_SFRP4', 'Lumsec_HLA', 'Mono_non_classical',
       'LummHR_active', 'Macro_IFN', 'CD4_activated', 'Fibro_major', 'pDC']


ann_vars_long = pd.melt(ann_vars, 
                        id_vars=meta_cols, 
                        value_vars=cell_cols,
                        var_name='cell_type',
                        value_name='z_score'
                        )
ann_vars_long

,chrom,snp_chromStart,snp_chromEnd,SNP,ref,alt,chrom_gene,tss,tss_chromEnd,strand,...,feature_type,overlapping_transcripts,genes_overlapping_variant,position_vs_tss,max_abs_z,max_abs_z_celltype,mean_z,n_celltypes_abs_z_ge_2,cell_type,z_score
0,1,45794979,45794980,1_45794979_C_G,C,G,1,45792568,45792569,+,...,intergenic,NaN,ENSG00000132781,downstream,0.202274,Fibro_SFRP4,-0.085161,0,Vas_venous,-0.097775
1,1,45794983,45794984,1_45794983_G_A,G,A,1,45792568,45792569,+,...,intergenic,NaN,ENSG00000132781,downstream,0.343143,Lumsec_HLA,-0.011812,0,Vas_venous,0.007582
2,1,45794993,45794994,1_45794993_G_A,G,A,1,45792568,45792569,+,...,intergenic,NaN,ENSG00000132781,downstream,0.525595,Fibro_SFRP4,-0.256749,0,Vas_venous,-0.284952
3,1,45794998,45794999,1_45794998_G_C,G,C,1,45792568,45792569,+,...,intergenic,NaN,ENSG00000132781,downstream,0.095425,LummHR_SCGB,0.037800,0,Vas_venous,0.050949
4,1,45795002,45795003,1_45795002_G_A,G,A,1,45792568,45792569,+,...,intergenic,NaN,ENSG00000132781,downstream,0.188081,Lymph_valve2,0.078857,0,Vas_venous,0.116439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546529,8,90996799,90996800,8_90996799_T_A,T,A,8,90996871,90996872,-,...,exonic_UTR,ENST00000265433;ENST00000396252;ENST0000049480...,ENSG00000104320,downstream,0.780899,Fibro_prematrix,-0.122596,0,pDC,-0.032397
546530,8,90996805,90996806,8_90996805_G_A,G,A,8,90996871,90996872,-,...,exonic_UTR,ENST00000265433;ENST00000396252;ENST0000049480...,ENSG00000104320,downstream,0.717763,mDC,-0.228630,0,pDC,-0.418884
546531,8,90996810,90996811,8_90996810_G_A,G,A,8,90996871,90996872,-,...,exonic_UTR,ENST00000265433;ENST00000396252;ENST0000049480...,ENSG00000104320,downstream,1.174331,CD8_activated,0.375588,0,pDC,0.282454
546532,8,90996815,90996816,8_90996815_C_T,C,T,8,90996871,90996872,-,...,exonic_UTR,ENST00000265433;ENST00000396252;ENST0000049480...,ENSG00000104320,downstream,1.790044,Lumsec_basal,0.979325,0,pDC,0.799901
546533,8,90996827,90996828,8_90996827_G_C,G,C,8,90996871,90996872,-,...,exonic_UTR,ENST00000265433;ENST00000396252;ENST0000049480...,ENSG00000104320,downstream,1.773325,Lumsec_prol,-0.945989,0,pDC,-1.191755

In [ ]:
sns.scatterplot(
    x=
)