In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("/storage/mathelierarea/processed/eirikhoy/action_var/data/BRCA1_BRCA2_PALB2_varianter_2025_02_10.csv")
df

      Unnamed: 0   Gene   Transcript           HGVSc               HGVSp Class
0              0  BRCA2  NM_000059.4        c.241T>A          p.Phe81Ile     2
1              1  BRCA2  NM_000059.4   c.316+1303A>G                 NaN    NP
2              2  BRCA2  NM_000059.4       c.1466C>G         p.Ser489Cys     1
3              3  BRCA2  NM_000059.4  c.2047_2050del  p.Ser683ArgfsTer46     5
4              4  BRCA2  NM_000059.4       c.2491G>A         p.Val831Ile     2
...          ...    ...          ...             ...                 ...   ...
1859        1859  BRCA2  NM_000059.3       c.8514A>G      c.8514A>G(p.=)     2
1860        1860  BRCA2  NM_000059.3       c.8663G>A        p.Arg2888His     2
1861        1861  BRCA2  NM_000059.3       c.9087G>T      c.9087G>T(p.=)     2
1862        1862  BRCA2  NM_000059.3       c.9150G>A      c.9150G>A(p.=)     2
1863        1863  BRCA2  NM_000059.4    c.9501+16A>C                 NaN     2

[1864 rows x 6 columns]

In [4]:
df.Gene.unique()

<ArrowStringArray>
['BRCA2', 'PALB2', 'BRCA1']
Length: 3, dtype: str

In [3]:
from io import StringIO
import pandas as pd
path = "/storage/mathelierarea/processed/eirikhoy/action_var/results/vep_output.txt"

with open(path) as f:
    lines = [l for l in f if not l.startswith('##')]

lines[0] = lines[0].lstrip('#')




vep = pd.read_csv(StringIO(''.join(lines)), sep='\t')
vep

,Uploaded_variation,Location,Allele,Gene,Feature,Feature_type,Consequence,cDNA_position,CDS_position,Protein_position,...,Existing_variation,IMPACT,DISTANCE,STRAND,FLAGS,REFSEQ_MATCH,REFSEQ_OFFSET,GIVEN_REF,USED_REF,BAM_EDIT
0,NM_000059.4:c.241T>A,13:32319250,A,675,NM_000059.4,Transcript,missense_variant,440,241,81,...,-,MODERATE,-,1,-,-,-,T,T,-
1,NM_000059.4:c.241T>A,13:32319250,A,646799,NM_001136571.2,Transcript,upstream_gene_variant,-,-,-,...,-,MODIFIER,3887,-1,-,-,-,T,T,-
2,NM_000059.4:c.241T>A,13:32319250,A,675,NM_001406719.1,Transcript,missense_variant,440,241,81,...,-,MODERATE,-,1,-,-,-,T,T,-
3,NM_000059.4:c.241T>A,13:32319250,A,675,NM_001406720.1,Transcript,missense_variant,440,241,81,...,-,MODERATE,-,1,-,-,-,T,T,-
4,NM_000059.4:c.241T>A,13:32319250,A,675,NM_001406721.1,Transcript,missense_variant,440,241,81,...,-,MODERATE,-,1,-,-,-,T,T,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109341,NM_000059.4:c.9501+16A>C,13:32394949,C,675,NM_001406719.1,Transcript,intron_variant,-,-,-,...,-,MODIFIER,-,1,-,-,-,A,A,-
109342,NM_000059.4:c.9501+16A>C,13:32394949,C,675,NM_001406720.1,Transcript,intron_variant,-,-,-,...,-,MODIFIER,-,1,-,-,-,A,A,-
109343,NM_000059.4:c.9501+16A>C,13:32394949,C,675,NM_001406721.1,Transcript,intron_variant,-,-,-,...,-,MODIFIER,-,1,-,-,-,A,A,-
109344,NM_000059.4:c.9501+16A>C,13:32394949,C,675,NM_001406722.1,Transcript,intron_variant,-,-,-,...,-,MODIFIER,-,1,-,-,-,A,A,-
109345,NM_000059.4:c.9501+16A>C,13:32394949,C,675,NR_176251.1,Transcript,"intron_variant,non_coding_transcript_variant",-,-,-,...,-,MODIFIER,-,1,-,-,-,A,A,-

In [4]:
vep.IMPACT.unique()

<ArrowStringArray>
['MODERATE', 'MODIFIER', 'HIGH', 'LOW']
Length: 4, dtype: str

In [5]:
vep[vep['IMPACT'] == 'HIGH']

,Uploaded_variation,Location,Allele,Gene,Feature,Feature_type,Consequence,cDNA_position,CDS_position,Protein_position,...,Existing_variation,IMPACT,DISTANCE,STRAND,FLAGS,REFSEQ_MATCH,REFSEQ_OFFSET,GIVEN_REF,USED_REF,BAM_EDIT
19,NM_000059.4:c.2047_2050del,13:32336402-32336405,-,675,NM_000059.4,Transcript,frameshift_variant,2246-2249,2047-2050,683-684,...,-,HIGH,-,1,-,-,-,TCTC,TCTC,-
20,NM_000059.4:c.2047_2050del,13:32336402-32336405,-,675,NM_001406719.1,Transcript,frameshift_variant,2246-2249,2047-2050,683-684,...,-,HIGH,-,1,-,-,-,TCTC,TCTC,-
21,NM_000059.4:c.2047_2050del,13:32336402-32336405,-,675,NM_001406720.1,Transcript,frameshift_variant,2246-2249,2047-2050,683-684,...,-,HIGH,-,1,-,-,-,TCTC,TCTC,-
43,NM_000059.4:c.5217_5223del,13:32339572-32339578,-,675,NM_000059.4,Transcript,frameshift_variant,5416-5422,5217-5223,1739-1741,...,-,HIGH,-,1,-,-,-,TTTAAGT,TTTAAGT,-
44,NM_000059.4:c.5217_5223del,13:32339572-32339578,-,675,NM_001406719.1,Transcript,frameshift_variant,5416-5422,5217-5223,1739-1741,...,-,HIGH,-,1,-,-,-,TTTAAGT,TTTAAGT,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97163,NM_007294.4:c.5407-2A>G,17:43047705,G,672,NM_007294.4,Transcript,splice_acceptor_variant,-,-,-,...,-,HIGH,-,-1,-,-,-,A,A,-
97164,NM_007294.4:c.5407-2A>G,17:43047705,G,672,NM_007297.4,Transcript,splice_acceptor_variant,-,-,-,...,-,HIGH,-,-1,-,-,-,A,A,-
97165,NM_007294.4:c.5407-2A>G,17:43047705,G,672,NM_007298.4,Transcript,splice_acceptor_variant,-,-,-,...,-,HIGH,-,-1,-,-,-,A,A,-
97166,NM_007294.4:c.5407-2A>G,17:43047705,G,672,NM_007299.4,Transcript,splice_acceptor_variant,-,-,-,...,-,HIGH,-,-1,-,-,-,A,A,-
97167,NM_007294.4:c.5407-2A>G,17:43047705,G,672,NM_007300.4,Transcript,splice_acceptor_variant,-,-,-,...,-,HIGH,-,-1,-,-,-,A,A,-